name: Context
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: dump
        run: |
          echo ${{ contains('hello', 'll') }}
          echo ${{ startsWith('hello', 'he') }}
          echo ${{ endsWith('hello', 'lo') }}
          echo ${{ format('Hello {0}{1}{2}', 'World', '!', '!') }}
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
  if-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Fail - TYPO
        run: eccho 'Fail!!!'
      - name: If failure
        if: failure()
        run: echo 'Run if previous step fail'
      - name: Always run - no matter if fail/success
        if: always
        run: echo 'Always run'
      - name: if previous success
        run: echo 'It runs if previous step success'
      - name: normal
        run: echo 'Normal'
      - name: normal-2
        run: echo 'normal-2'