name:  Decrypt File

on: push

jobs:
  decrypt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Decrypt File
        env:
          PASSPHRASE: ${{ secrets.MY_SECRET }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE"--output=$HOME/my_secret.json my_secret.json.gpg
      - name: Print file content
        run: cat $HOME/my_secret.json